### ISSUE TITLE
Unable to Join MP 1.17 Server - Registry Remapping Failed

### ISSUE THREAD

**Issue by kalinzange** [MrKacafirekCZ/doggomod#5]
```
[22:24:56] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:entity_type contains IDs unknown to the receiver!
 - minecraft:wolf
	at net.minecraft.class_2370.remap(class_2370.java:1194) ~[intermediary-1.17.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:283) ~[b7f79356-a75f-42cb-b065-2aab3a251b39.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:89) ~[b7f79356-a75f-42cb-b065-2aab3a251b39.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-1.17.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.17.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-1.17.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1077) [intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```

If I remove this mod from the client I can join the server normally

**Comment by MrKacafirekCZ** [comment]
As the README currently says:

> Warning! Currently this mod only works in Singleplayer and I don't know if it will ever work in Multiplayer. Issues that I'm running into are very weird and difficult to fix.

**Comment by kalinzange** [comment]
> As the README currently says:
> 
> > Warning! Currently this mod only works in Singleplayer and I don't know if it will ever work in Multiplayer. Issues that I'm running into are very weird and difficult to fix.

Apologies for it
